### ISSUE TITLE
Error in symphony-api.js

### ISSUE THREAD

**Issue by BhaskaranR** [symphonyoss/extension-api-examples#21]
I followed the steps exactly mentioned in setting up the example api. I am getting an exception when i run the app. 
```
Uncaught TypeError: watcher.getTheme is not a function
    at receiveMessage (symphony-api.js:formatted:2376)
```
watcher returns false  when data.command is "hello". did i miss anything? or could it be due to the proxy settings? 

the error occurs in symphony.js v1.0
```
     if ("hello" === data.command) {
                    var watcher = SYMPHONY.services.subscribe("theme-watcher")
```

**Comment by Ondoher** [comment]
Are you running the application inside the the Symphony web client, or standalone?

**Comment by BhaskaranR** [comment]
standalone

**Comment by Ondoher** [comment]
Okay, the API is not designed to be used in a standalone application, but only in support of extension apps. However, that error also should not cause any problems. It happens because when an app has no parent window, then its window becomes its own parent. So, you are sending messages to yourself. And the API gets confused.

**Comment by BhaskaranR** [comment]
ok makes sense. let me close the issue
